platform :ios, '9.2'

inhibit_all_warnings!

def mainPods
    pod 'AFNetworking', '~> 3.1.0'
    pod 'GDataXML-HTML', '~> 1.3.0'
    pod 'Toast', '~> 3.0'
end

def testingPods
    pod 'OHHTTPStubs', '~> 5.0'
    pod 'OCMock', '~> 3.3'
end

target 'SimplePictureClient' do
    mainPods
end

target 'SimplePictureClientTests' do
    mainPods
    testingPods
end
